# fly.toml app configuration file for edn

app = "edn"
primary_region = "fra"

[build]
  # Tu peux préciser un builder Node.js si besoin, sinon Fly.io détecte automatiquement
  
[[mounts]]
source = "data"
destination = "/data"

[http_service]
  internal_port = 3000        # Le port sur lequel ton serveur Express écoute
  force_https = true
  auto_start_machines = true
  min_machines_running = 1    # Toujours 1 machine active pour ton bot
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"

